# Generated by Django 5.2.4 on 2026-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieNightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movienight/generated/')),
                ('prompt_used', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
