# Generated by Django 5.2.4 on 2026-07-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienight', '0002_movienightimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('random', 'Random'), ('curated', 'Curated')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(blank=True)),
                ('chosen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
