# Generated by Django 5.2.4 on 2025-08-17 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('ammo_type', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_clips', to='gunSounds.gun')),
            ],
        ),
    ]
