# Generated by Django 4.2.11 on 2025-07-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun_name', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
