# Generated by Django 4.2.11 on 2025-07-26 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gunSounds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gun',
            old_name='gun_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gun',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='gun',
            name='ammo_type',
            field=models.CharField(default='compact', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gun',
            name='image',
            field=models.ImageField(default='compact', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gun',
            name='size',
            field=models.CharField(default='compact', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_clips', to='gunSounds.gun')),
            ],
        ),
    ]
