# Generated by Django 5.2.4 on 2025-12-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunSounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='distance',
            field=models.CharField(choices=[('100m', '100m'), ('200m', '200m'), ('320m', '320m'), ('400m', '400m'), ('500m', '500m')], default='100m', max_length=10),
        ),
    ]
