# Generated by Django 5.2.4 on 2026-01-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunSounds', '0003_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('map_name', models.CharField(default='stillwater', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('marker_type', models.CharField(default='spawn', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='audioclip',
            name='distance',
            field=models.CharField(choices=[('100m', '100m'), ('200m', '200m'), ('320m', '320m'), ('400m', '400m'), ('490m', '490m')], default='100m', max_length=10),
        ),
    ]
