# Generated by Django 5.2.4 on 2026-07-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunSounds', '0004_mapmarker_alter_audioclip_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmarker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='markers/'),
        ),
    ]
